name = "zed-ai-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

[env.production.vars]
# 生产环境变量将在 Cloudflare Dashboard 中配置
# OPENAI_API_KEY = "your_openai_api_key_here"

[env.development.vars]
# 开发环境变量
# OPENAI_API_KEY = "your_openai_api_key_here"

# 路由配置
[[env.production.routes]]
pattern = "api.yourdomain.com/*"
zone_name = "yourdomain.com"

# 或者使用 workers.dev 子域名
# 部署后会得到类似: zed-ai-worker.your-subdomain.workers.dev